"""Apply the Licaris editorial copy to all supported languages."""
import json
from pathlib import Path

COPY = {
 'fr': ['Une aventure entre amis', 'L’aventure, ensemble.', 'Des Pokémon à rencontrer, un monde à explorer et des amis avec qui partager l’aventure. Découvrez Cobblemon dans Minecraft, composez votre équipe et écrivez votre histoire sur Licaris.', 'Rejoindre Licaris', 'Huit projets Minecraft. Une même communauté.', 'Pour Licaris, notre aventure Pokémon sur Minecraft avec Cobblemon, retrouvez les informations d’accès sur le Discord du projet.'],
 'en': ['An adventure with friends', 'Adventure, together.', 'Pokémon to meet, a world to explore and friends to share the adventure with. Discover Cobblemon in Minecraft, build your team and write your story on Licaris.', 'Join Licaris', 'Eight Minecraft projects. One community.', 'For Licaris, our Pokémon adventure in Minecraft with Cobblemon, visit the project’s Discord for access information.'],
 'de': ['Ein Abenteuer mit Freunden', 'Gemeinsam ins Abenteuer.', 'Pokémon treffen, eine Welt erkunden und Abenteuer mit Freunden teilen. Entdecke Cobblemon in Minecraft, stelle dein Team zusammen und schreibe deine Geschichte auf Licaris.', 'Licaris beitreten', 'Acht Minecraft-Projekte. Eine Community.', 'Informationen zum Zugang zu Licaris, unserem Pokémon-Abenteuer in Minecraft mit Cobblemon, findest du auf dem Discord des Projekts.'],
 'es': ['Una aventura entre amigos', 'La aventura, juntos.', 'Pokémon que conocer, un mundo que explorar y amigos con quienes compartir la aventura. Descubre Cobblemon en Minecraft, forma tu equipo y escribe tu historia en Licaris.', 'Unirse a Licaris', 'Ocho proyectos de Minecraft. Una comunidad.', 'Para acceder a Licaris, nuestra aventura Pokémon en Minecraft con Cobblemon, consulta el Discord del proyecto.'],
 'it': ['Un’avventura tra amici', 'L’avventura, insieme.', 'Pokémon da incontrare, un mondo da esplorare e amici con cui condividere l’avventura. Scopri Cobblemon in Minecraft, crea la tua squadra e scrivi la tua storia su Licaris.', 'Unisciti a Licaris', 'Otto progetti Minecraft. Una comunità.', 'Per le informazioni di accesso a Licaris, la nostra avventura Pokémon in Minecraft con Cobblemon, visita il Discord del progetto.'],
 'pt': ['Uma aventura entre amigos', 'A aventura, juntos.', 'Pokémon para conhecer, um mundo para explorar e amigos com quem partilhar a aventura. Descobre Cobblemon no Minecraft, cria a tua equipa e escreve a tua história no Licaris.', 'Juntar-me ao Licaris', 'Oito projetos Minecraft. Uma comunidade.', 'Para saber como aceder ao Licaris, a nossa aventura Pokémon no Minecraft com Cobblemon, visita o Discord do projeto.'],
 'nl': ['Een avontuur met vrienden', 'Samen op avontuur.', 'Pokémon ontmoeten, een wereld verkennen en avonturen met vrienden delen. Ontdek Cobblemon in Minecraft, stel je team samen en schrijf je verhaal op Licaris.', 'Doe mee met Licaris', 'Acht Minecraft-projecten. Eén community.', 'Informatie over toegang tot Licaris, ons Pokémon-avontuur in Minecraft met Cobblemon, vind je op de Discord van het project.'],
 'pl': ['Przygoda z przyjaciółmi', 'Razem po przygodę.', 'Pokémony do poznania, świat do odkrycia i przyjaciele, z którymi przeżyjesz przygodę. Odkryj Cobblemon w Minecraft, stwórz drużynę i napisz swoją historię na Licaris.', 'Dołącz do Licaris', 'Osiem projektów Minecraft. Jedna społeczność.', 'Informacje o dostępie do Licaris, naszej przygody Pokémon w Minecraft z Cobblemon, znajdziesz na Discordzie projektu.'],
 'tr': ['Arkadaşlarla bir macera', 'Birlikte maceraya.', 'Tanışılacak Pokémonlar, keşfedilecek bir dünya ve macerayı paylaşacak arkadaşlar. Minecraft’ta Cobblemon’u keşfet, takımını kur ve Licaris’te kendi hikâyeni yaz.', 'Licaris’e katıl', 'Sekiz Minecraft projesi. Tek topluluk.', 'Minecraft’ta Cobblemon ile Pokémon maceramız Licaris’e erişim bilgileri için projenin Discord sunucusunu ziyaret et.'],
 'ru': ['Приключение с друзьями', 'Навстречу приключениям. Вместе.', 'Знакомьтесь с покемонами, исследуйте мир и делитесь приключениями с друзьями. Откройте Cobblemon в Minecraft, соберите команду и создайте свою историю на Licaris.', 'Присоединиться к Licaris', 'Восемь проектов Minecraft. Одно сообщество.', 'Информация о доступе к Licaris, нашему приключению с покемонами в Minecraft с Cobblemon, доступна в Discord проекта.'],
 'ar': ['مغامرة مع الأصدقاء', 'المغامرة، معًا.', 'بوكيمونات لتتعرف عليها، وعالم لتستكشفه، وأصدقاء لتشاركهم المغامرة. اكتشف Cobblemon في Minecraft، وكوّن فريقك واكتب قصتك في Licaris.', 'انضم إلى Licaris', 'ثمانية مشاريع Minecraft. مجتمع واحد.', 'لمعرفة طريقة الانضمام إلى Licaris، مغامرتنا مع البوكيمون في Minecraft باستخدام Cobblemon، زر خادم Discord الخاص بالمشروع.'],
 'hi': ['दोस्तों के साथ एक रोमांच', 'मिलकर चलें रोमांच की ओर।', 'पोकेमॉन से मिलें, एक नई दुनिया खोजें और दोस्तों के साथ रोमांच साझा करें। Minecraft में Cobblemon खोजें, अपनी टीम बनाएँ और Licaris पर अपनी कहानी लिखें।', 'Licaris से जुड़ें', 'आठ Minecraft प्रोजेक्ट। एक समुदाय।', 'Minecraft में Cobblemon के साथ हमारे पोकेमॉन रोमांच Licaris से जुड़ने की जानकारी प्रोजेक्ट के Discord पर मिलेगी।'],
 'id': ['Petualangan bersama teman', 'Bertualang, bersama.', 'Pokémon untuk ditemui, dunia untuk dijelajahi, dan teman untuk berbagi petualangan. Temukan Cobblemon di Minecraft, bentuk timmu, dan tulis kisahmu di Licaris.', 'Gabung Licaris', 'Delapan proyek Minecraft. Satu komunitas.', 'Untuk informasi akses ke Licaris, petualangan Pokémon kami di Minecraft dengan Cobblemon, kunjungi Discord proyek ini.'],
 'ja': ['仲間と楽しむ冒険', '一緒に、冒険へ。', '出会いを待つポケモン、広がる世界、冒険を分かち合う仲間。MinecraftでCobblemonを体験し、自分のチームを作って、Licarisであなたの物語を紡ぎましょう。', 'Licarisに参加する', '8つのMinecraftプロジェクト。ひとつのコミュニティ。', 'MinecraftとCobblemonでポケモンの冒険を楽しむLicarisへの参加方法は、プロジェクトのDiscordでご確認ください。'],
 'ko': ['친구들과 함께하는 모험', '함께 떠나는 모험.', '만나고 싶은 포켓몬, 탐험할 세계, 모험을 함께할 친구들. Minecraft에서 Cobblemon을 만나고, 나만의 팀을 만들어 Licaris에서 이야기를 써 내려가세요.', 'Licaris 참여하기', '여덟 개의 Minecraft 프로젝트. 하나의 커뮤니티.', 'Minecraft와 Cobblemon으로 즐기는 포켓몬 모험 Licaris의 참여 방법은 프로젝트 Discord에서 확인하세요.'],
 'zh': ['与好友一起冒险', '一起，开启冒险。', '结识宝可梦，探索广阔世界，与好友分享冒险。在 Minecraft 中体验 Cobblemon，组建自己的队伍，在 Licaris 书写你的故事。', '加入 Licaris', '八个 Minecraft 项目，同一个社区。', 'Licaris 是我们基于 Minecraft 和 Cobblemon 打造的宝可梦冒险，加入方式请查看项目的 Discord。'],
}

if __name__ == '__main__':
    for path in (Path(__file__).resolve().parents[1] / 'app/locales').glob('*.json'):
        values = COPY[path.stem]
        assert len(values) == 6, path
        data = json.loads(path.read_text(encoding='utf-8'))
        for key, value in zip(['licarisStatus', 'licarisLine', 'licarisText', 'licarisCta', 'discordTagline'], values[:5]):
            data[key] = value
        if values[5] not in data['faq2A']:
            data['faq2A'] += ' ' + values[5]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
